# Definition of all trackable objects (rigid bodies) and their respective
# pose topics and TF frame name (child_frame_id).
#
# The marker ID corresponds to the *User Data* field in the Motive
#  configuration.

rigid_bodies:
    '39':
        pose: /vrpn_client_node/Ilaria1/pose
        pose2d: /vrpn_client_node/Ilaria1/ground_pose
        child_frame_id: /vrpn_client_node/Ilaria1/base_link
        parent_frame_id: world
    '40':
        pose: /vrpn_client_node/Ilaria2/pose
        pose2d: /vrpn_client_node/Ilaria2/ground_pose
        child_frame_id: /vrpn_client_node/Ilaria2/base_link
        parent_frame_id: world
    '41':
        pose: /vrpn_client_node/Ilaria3/pose
        pose2d: /vrpn_client_node/Ilaria3/ground_pose
        child_frame_id: /vrpn_client_node/Ilaria3/base_link
        parent_frame_id: world

# Configuration options at EPFL
optitrack_config:
        multicast_address: 239.255.42.99
